### PR TITLE
Minor UI/UX changes

### LINKED ISSUE #27: No(Number) prefix used even with non-numerical semester names
Profile page shows SGPA information as, 
```
Semester No:
SGPA:
```
But some branches have semester value as _final_ and possibly some other string, in those cases _No_ prefix sounds wrong. It will be better to remove _No_ prefix altogether, as it will sound good with both numerical and non-numerical semester names.

### PR DESCRIPTION
**Pull request by manorit2001**
closes #27 #26 #24

### CODE REVIEW

**Review by parth-07 — COMMENTED** [review]
Can you make dialog box to have values YES/CANCEL instead of OK/CANCEL, 
_Do you really want to delete semester 1 result?_ , _Yes_ sounds better than _ok_ for questions like this, what do you think ?

**Comment by manorit2001** [comment]
> Can you make dialog box to have values YES/CANCEL instead of OK/CANCEL,
> _Do you really want to delete semester 1 result?_ , _Yes_ sounds better than _ok_ for questions like this, what do you think ?

I am not really sure but I'll check once regarding this, also do you want this to be the same in `sign out` confirmation also?

**Review by parth-07 — DISMISSED** [review]
LGTM

**Comment by parth-07** [comment]
> > Can you make dialog box to have values YES/CANCEL instead of OK/CANCEL,
> > _Do you really want to delete semester 1 result?_ , _Yes_ sounds better than _ok_ for questions like this, what do you think ?
> 
> I am not really sure but I'll check once regarding this, also do you want this to be the same in `sign out` confirmation also?
>

Yes, I would like this to be same in `sign out` confirmation page too.
 
> Edit: I just checked and I am using default value given by `android.R` packages i.e `android.R.string.yes` for postive response and `android.R.string.no` for negative responses and apparently those values contains `OK/CANCEL`. Should I change them?

Yes/Cancel or Yes/No, sounds better than Ok/Cancel for certain questions, so I think yes we should change these, what do you think ?

**Comment by manorit2001** [comment]
> Yes/Cancel or Yes/No, sounds better than Ok/Cancel for certain questions, so I think yes we should change these, what do you think ?

Sounds right, I replaced all ok/cancel with yes/no as they seemed yes/no questions only

**Review by parth-07 — APPROVED** [review]
Looks good :)

**Pull request merged**
